import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Database } from '@/integrations/supabase/types';

type ProductionStatus = Database['public']['Enums']['production_status'];

export interface Machine {
  id: string;
  name: string;
  description: string | null;
  status: string;
  purchase_date: string | null;
  purchase_cost: number;
  current_value: number;
  depreciation_rate: number;
  last_maintenance: string | null;
}

export interface RawMaterial {
  id: string;
  name: string;
  description: string | null;
  unit: string;
  unit_cost: number;
  quantity_in_stock: number;
  reorder_level: number;
}

export interface ProductionRun {
  id: string;
  batch_number: string;
  product_id: string;
  variant_id: string | null;
  machine_id: string | null;
  planned_quantity: number;
  actual_quantity: number;
  wastage_quantity: number;
  status: ProductionStatus;
  start_date: string;
  end_date: string | null;
  production_cost: number;
  notes: string | null;
  product?: { name: string };
  machine?: Machine;
}

export function useProductionRuns() {
  return useQuery({
    queryKey: ['production_runs'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('production_runs')
        .select(`
          *,
          product:products(name),
          machine:machines(*)
        `)
        .order('created_at', { ascending: false })
        .limit(10);
      
      if (error) throw error;
      return data as ProductionRun[];
    },
  });
}

export function useMachines() {
  return useQuery({
    queryKey: ['machines'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('machines')
        .select('*')
        .order('name');
      
      if (error) throw error;
      return data as Machine[];
    },
  });
}

export function useRawMaterials() {
  return useQuery({
    queryKey: ['raw_materials'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('raw_materials')
        .select('*')
        .order('name');
      
      if (error) throw error;
      return data as RawMaterial[];
    },
  });
}

export function useCreateProductionRun() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (run: { 
      product_id: string; 
      variant_id?: string; 
      machine_id?: string; 
      planned_quantity: number;
      start_date?: string;
      notes?: string;
    }) => {
      const { data, error } = await supabase
        .from('production_runs')
        .insert({
          ...run,
          batch_number: '', // Will be auto-generated by trigger
          status: 'in_progress',
          actual_quantity: 0,
          wastage_quantity: 0,
          start_date: run.start_date || new Date().toISOString(),
        })
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['production_runs'] });
      toast.success('Production run created successfully');
    },
    onError: (error) => {
      toast.error('Failed to create production run: ' + error.message);
    },
  });
}

export function useUpdateProductionRun() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ 
      id, 
      status, 
      actual_quantity, 
      wastage_quantity 
    }: { 
      id: string; 
      status?: ProductionStatus | null; 
      actual_quantity?: number; 
      wastage_quantity?: number; 
    }) => {
      const updates: Record<string, any> = {
        updated_at: new Date().toISOString(),
      };

      if (typeof status !== 'undefined') {
        updates.status = status;
        updates.end_date = status === 'completed' ? new Date().toISOString() : null;
      }
      if (typeof actual_quantity !== 'undefined') updates.actual_quantity = actual_quantity;
      if (typeof wastage_quantity !== 'undefined') updates.wastage_quantity = wastage_quantity;

      const { error } = await supabase
        .from('production_runs')
        .update(updates)
        .eq('id', id);

      if (error) throw error;
      return { id, ...updates };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['production_runs'] });
      toast.success('Production run updated');
    },
    onError: (error) => {
      toast.error('Failed to update production run: ' + error.message);
    },
  });
}

type RawMaterialInput = {
  name: string;
  description?: string;
  unit: string;
  unit_cost?: number;
  quantity_in_stock?: number;
  reorder_level?: number;
};

export function useCreateRawMaterial() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (material: RawMaterialInput) => {
      const { data, error } = await supabase
        .from('raw_materials')
        .insert(material)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['raw_materials'] });
      toast.success('Raw material saved');
    },
    onError: (error) => {
      toast.error('Failed to save material: ' + error.message);
    },
  });
}

export function useRestockRawMaterial() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ materialId, quantity, unit_cost }: { materialId: string; quantity: number; unit_cost?: number }) => {
      const { data: existing, error: fetchError } = await supabase
        .from('raw_materials')
        .select('quantity_in_stock, unit_cost')
        .eq('id', materialId)
        .maybeSingle();

      if (fetchError) throw fetchError;

      const currentQty = Number(existing?.quantity_in_stock || 0);
      const newQty = currentQty + quantity;

      const { error } = await supabase
        .from('raw_materials')
        .update({
          quantity_in_stock: newQty,
          unit_cost: typeof unit_cost === 'number' ? unit_cost : existing?.unit_cost || null,
          updated_at: new Date().toISOString(),
        })
        .eq('id', materialId);

      if (error) throw error;
      return { materialId, newQty };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['raw_materials'] });
      toast.success('Stock updated');
    },
    onError: (error) => {
      toast.error('Failed to restock: ' + error.message);
    },
  });
}

type MachineInput = {
  name: string;
  description?: string;
  status?: string;
  purchase_date?: string | null;
  purchase_cost?: number | null;
  current_value?: number | null;
  depreciation_rate?: number | null;
  last_maintenance?: string | null;
};

export function useRegisterMachine() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (machine: MachineInput) => {
      const { data, error } = await supabase
        .from('machines')
        .insert(machine)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['machines'] });
      toast.success('Machine saved');
    },
    onError: (error) => {
      toast.error('Failed to save machine: ' + error.message);
    },
  });
}

export function useUpdateMachine() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...machine }: MachineInput & { id: string }) => {
      const { error } = await supabase
        .from('machines')
        .update(machine)
        .eq('id', id);

      if (error) throw error;
      return { id, ...machine };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['machines'] });
      toast.success('Machine updated');
    },
    onError: (error) => {
      toast.error('Failed to update machine: ' + error.message);
    },
  });
}
