import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Database } from '@/integrations/supabase/types';

type ProductionStatus = Database['public']['Enums']['production_status'];

export interface Machine {
  id: string;
  name: string;
  description: string | null;
  status: string;
  purchase_date: string | null;
  purchase_cost: number;
  current_value: number;
  depreciation_rate: number;
  last_maintenance: string | null;
}

export interface RawMaterial {
  id: string;
  name: string;
  description: string | null;
  unit: string;
  unit_cost: number;
  quantity_in_stock: number;
  reorder_level: number;
}

export interface ProductionRun {
  id: string;
  batch_number: string;
  product_id: string;
  variant_id: string | null;
  machine_id: string | null;
  planned_quantity: number;
  actual_quantity: number;
  wastage_quantity: number;
  status: ProductionStatus;
  start_date: string;
  end_date: string | null;
  production_cost: number;
  notes: string | null;
  product?: { name: string };
  machine?: Machine;
}

export function useProductionRuns() {
  return useQuery({
    queryKey: ['production_runs'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('production_runs')
        .select(`
          *,
          product:products(name),
          machine:machines(*)
        `)
        .order('created_at', { ascending: false })
        .limit(10);
      
      if (error) throw error;
      return data as ProductionRun[];
    },
  });
}

export function useMachines() {
  return useQuery({
    queryKey: ['machines'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('machines')
        .select('*')
        .order('name');
      
      if (error) throw error;
      return data as Machine[];
    },
  });
}

export function useRawMaterials() {
  return useQuery({
    queryKey: ['raw_materials'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('raw_materials')
        .select('*')
        .order('name');
      
      if (error) throw error;
      return data as RawMaterial[];
    },
  });
}

export function useCreateProductionRun() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (run: { product_id: string; variant_id?: string; machine_id?: string; planned_quantity: number }) => {
      const { data, error } = await supabase
        .from('production_runs')
        .insert({
          ...run,
          batch_number: '', // Will be auto-generated by trigger
        })
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['production_runs'] });
      toast.success('Production run created successfully');
    },
    onError: (error) => {
      toast.error('Failed to create production run: ' + error.message);
    },
  });
}
