// This file is automatically generated. Do not edit directly.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      creditor_transactions: {
        Row: {
          amount: number
          created_at: string | null
          created_by: string | null
          creditor_id: string
          id: string
          notes: string | null
          reference_number: string | null
          transaction_type: string
        }
        Insert: {
          amount: number
          created_at?: string | null
          created_by?: string | null
          creditor_id: string
          id?: string
          notes?: string | null
          reference_number?: string | null
          transaction_type: string
        }
        Update: {
          amount?: number
          created_at?: string | null
          created_by?: string | null
          creditor_id?: string
          id?: string
          notes?: string | null
          reference_number?: string | null
          transaction_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "creditor_transactions_creditor_id_fkey"
            columns: ["creditor_id"]
            isOneToOne: false
            referencedRelation: "creditors"
            referencedColumns: ["id"]
          },
        ]
      }
      creditors: {
        Row: {
          address: string | null
          contact_person: string | null
          created_at: string | null
          created_by: string | null
          email: string | null
          id: string
          is_active: boolean | null
          name: string
          outstanding_balance: number
          phone: string | null
          updated_at: string | null
        }
        Insert: {
          address?: string | null
          contact_person?: string | null
          created_at?: string | null
          created_by?: string | null
          email?: string | null
          id?: string
          is_active?: boolean | null
          name: string
          outstanding_balance?: number
          phone?: string | null
          updated_at?: string | null
        }
        Update: {
          address?: string | null
          contact_person?: string | null
          created_at?: string | null
          created_by?: string | null
          email?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
          outstanding_balance?: number
          phone?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      customers: {
        Row: {
          address: string | null
          created_at: string | null
          created_by: string | null
          credit_balance: number | null
          credit_limit: number | null
          customer_type: Database["public"]["Enums"]["customer_type"]
          email: string | null
          id: string
          is_active: boolean | null
          name: string
          parent_customer_id: string | null
          phone: string | null
          settlement_day: string | null
          updated_at: string | null
        }
        Insert: {
          address?: string | null
          created_at?: string | null
          created_by?: string | null
          credit_balance?: number | null
          credit_limit?: number | null
          customer_type?: Database["public"]["Enums"]["customer_type"]
          email?: string | null
          id?: string
          is_active?: boolean | null
          name: string
          parent_customer_id?: string | null
          phone?: string | null
          settlement_day?: string | null
          updated_at?: string | null
        }
        Update: {
          address?: string | null
          created_at?: string | null
          created_by?: string | null
          credit_balance?: number | null
          credit_limit?: number | null
          customer_type?: Database["public"]["Enums"]["customer_type"]
          email?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
          parent_customer_id?: string | null
          phone?: string | null
          settlement_day?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customers_parent_customer_id_fkey"
            columns: ["parent_customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      employees: {
        Row: {
          basic_salary: number | null
          created_at: string | null
          department: string | null
          email: string | null
          employee_number: string
          full_name: string
          hire_date: string | null
          id: string
          is_active: boolean | null
          phone: string | null
          position: string | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          basic_salary?: number | null
          created_at?: string | null
          department?: string | null
          email?: string | null
          employee_number: string
          full_name: string
          hire_date?: string | null
          id?: string
          is_active?: boolean | null
          phone?: string | null
          position?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          basic_salary?: number | null
          created_at?: string | null
          department?: string | null
          email?: string | null
          employee_number?: string
          full_name?: string
          hire_date?: string | null
          id?: string
          is_active?: boolean | null
          phone?: string | null
          position?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      expenses: {
        Row: {
          amount: number
          approved_by: string | null
          category: string
          created_at: string | null
          created_by: string | null
          description: string
          expense_date: string
          id: string
          is_manufacturing_cost: boolean | null
          payment_method: Database["public"]["Enums"]["payment_method"] | null
          reference_number: string | null
        }
        Insert: {
          amount: number
          approved_by?: string | null
          category: string
          created_at?: string | null
          created_by?: string | null
          description: string
          expense_date: string
          id?: string
          is_manufacturing_cost?: boolean | null
          payment_method?: Database["public"]["Enums"]["payment_method"] | null
          reference_number?: string | null
        }
        Update: {
          amount?: number
          approved_by?: string | null
          category?: string
          created_at?: string | null
          created_by?: string | null
          description?: string
          expense_date?: string
          id?: string
          is_manufacturing_cost?: boolean | null
          payment_method?: Database["public"]["Enums"]["payment_method"] | null
          reference_number?: string | null
        }
        Relationships: []
      }
      inventory: {
        Row: {
          created_at: string | null
          id: string
          last_stock_date: string | null
          quantity: number
          reserved_quantity: number | null
          updated_at: string | null
          variant_id: string
          warehouse_location: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          last_stock_date?: string | null
          quantity?: number
          reserved_quantity?: number | null
          updated_at?: string | null
          variant_id: string
          warehouse_location?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          last_stock_date?: string | null
          quantity?: number
          reserved_quantity?: number | null
          updated_at?: string | null
          variant_id?: string
          warehouse_location?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "inventory_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: true
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_transactions: {
        Row: {
          created_at: string | null
          created_by: string | null
          id: string
          new_quantity: number
          notes: string | null
          previous_quantity: number
          quantity_change: number
          reference_id: string | null
          reference_type: string | null
          transaction_type: string
          variant_id: string
        }
        Insert: {
          created_at?: string | null
          created_by?: string | null
          id?: string
          new_quantity: number
          notes?: string | null
          previous_quantity: number
          quantity_change: number
          reference_id?: string | null
          reference_type?: string | null
          transaction_type: string
          variant_id: string
        }
        Update: {
          created_at?: string | null
          created_by?: string | null
          id?: string
          new_quantity?: number
          notes?: string | null
          previous_quantity?: number
          quantity_change?: number
          reference_id?: string | null
          reference_type?: string | null
          transaction_type?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_transactions_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      machines: {
        Row: {
          created_at: string | null
          current_value: number | null
          depreciation_rate: number | null
          description: string | null
          id: string
          last_maintenance: string | null
          name: string
          purchase_cost: number | null
          purchase_date: string | null
          status: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          current_value?: number | null
          depreciation_rate?: number | null
          description?: string | null
          id?: string
          last_maintenance?: string | null
          name: string
          purchase_cost?: number | null
          purchase_date?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          current_value?: number | null
          depreciation_rate?: number | null
          description?: string | null
          id?: string
          last_maintenance?: string | null
          name?: string
          purchase_cost?: number | null
          purchase_date?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      payments: {
        Row: {
          amount: number
          created_at: string | null
          customer_id: string | null
          id: string
          order_id: string | null
          payment_method: Database["public"]["Enums"]["payment_method"]
          status: string | null
        }
        Insert: {
          amount: number
          created_at?: string | null
          customer_id?: string | null
          id?: string
          order_id?: string | null
          payment_method: Database["public"]["Enums"]["payment_method"]
          status?: string | null
        }
        Update: {
          amount?: number
          created_at?: string | null
          customer_id?: string | null
          id?: string
          order_id?: string | null
          payment_method?: Database["public"]["Enums"]["payment_method"]
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "sales_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      payroll_entries: {
        Row: {
          allowances: number | null
          basic_salary: number
          created_at: string | null
          created_by: string | null
          deductions: number | null
          employee_id: string
          id: string
          net_salary: number
          notes: string | null
          pay_date: string
          pay_period_end: string
          pay_period_start: string
          status: string | null
        }
        Insert: {
          allowances?: number | null
          basic_salary: number
          created_at?: string | null
          created_by?: string | null
          deductions?: number | null
          employee_id: string
          id?: string
          net_salary: number
          notes?: string | null
          pay_date: string
          pay_period_end: string
          pay_period_start: string
          status?: string | null
        }
        Update: {
          allowances?: number | null
          basic_salary?: number
          created_at?: string | null
          created_by?: string | null
          deductions?: number | null
          employee_id?: string
          id?: string
          net_salary?: number
          notes?: string | null
          pay_date?: string
          pay_period_end?: string
          pay_period_start?: string
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payroll_entries_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      product_categories: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          parent_id: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          parent_id?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          parent_id?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "product_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      product_variants: {
        Row: {
          barcode: string | null
          color: string | null
          cost_price: number
          created_at: string | null
          id: string
          is_active: boolean | null
          price: number
          product_id: string
          reorder_level: number | null
          size: string | null
          sku: string
          updated_at: string | null
          variant_name: string
          weight: number | null
        }
        Insert: {
          barcode?: string | null
          color?: string | null
          cost_price?: number
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          price?: number
          product_id: string
          reorder_level?: number | null
          size?: string | null
          sku: string
          updated_at?: string | null
          variant_name: string
          weight?: number | null
        }
        Update: {
          barcode?: string | null
          color?: string | null
          cost_price?: number
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          price?: number
          product_id?: string
          reorder_level?: number | null
          size?: string | null
          sku?: string
          updated_at?: string | null
          variant_name?: string
          weight?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "product_variants_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      production_materials: {
        Row: {
          created_at: string | null
          id: string
          production_run_id: string | null
          quantity_used: number
          raw_material_id: string | null
          unit_cost: number | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          production_run_id?: string | null
          quantity_used: number
          raw_material_id?: string | null
          unit_cost?: number | null
        }
        Update: {
          created_at?: string | null
          id?: string
          production_run_id?: string | null
          quantity_used?: number
          raw_material_id?: string | null
          unit_cost?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "production_materials_production_run_id_fkey"
            columns: ["production_run_id"]
            isOneToOne: false
            referencedRelation: "production_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_materials_raw_material_id_fkey"
            columns: ["raw_material_id"]
            isOneToOne: false
            referencedRelation: "raw_materials"
            referencedColumns: ["id"]
          },
        ]
      }
      production_runs: {
        Row: {
          actual_quantity: number | null
          batch_number: string
          created_at: string | null
          created_by: string | null
          end_date: string | null
          id: string
          machine_id: string | null
          notes: string | null
          planned_quantity: number
          production_cost: number | null
          recipe_id: string | null
          start_date: string | null
          status: string
        }
        Insert: {
          actual_quantity?: number | null
          batch_number: string
          created_at?: string | null
          created_by?: string | null
          end_date?: string | null
          id?: string
          machine_id?: string | null
          notes?: string | null
          planned_quantity: number
          production_cost?: number | null
          recipe_id?: string | null
          start_date?: string | null
          status: string
        }
        Update: {
          actual_quantity?: number | null
          batch_number?: string
          created_at?: string | null
          created_by?: string | null
          end_date?: string | null
          id?: string
          machine_id?: string | null
          notes?: string | null
          planned_quantity?: number
          production_cost?: number | null
          recipe_id?: string | null
          start_date?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "production_runs_machine_id_fkey"
            columns: ["machine_id"]
            isOneToOne: false
            referencedRelation: "machines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_runs_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          attributes: Json | null
          base_price: number
          category_id: string | null
          cost_price: number
          created_at: string | null
          created_by: string | null
          description: string | null
          id: string
          image_url: string | null
          is_active: boolean | null
          name: string
          updated_at: string | null
        }
        Insert: {
          attributes?: Json | null
          base_price?: number
          category_id?: string | null
          cost_price?: number
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          name: string
          updated_at?: string | null
        }
        Update: {
          attributes?: Json | null
          base_price?: number
          category_id?: string | null
          cost_price?: number
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          name: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "product_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          device_id: string | null
          email: string
          full_name: string
          id: string
          is_active: boolean | null
          phone: string | null
          updated_at: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          device_id?: string | null
          email: string
          full_name: string
          id: string
          is_active?: boolean | null
          phone?: string | null
          updated_at?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          device_id?: string | null
          email?: string
          full_name?: string
          id?: string
          is_active?: boolean | null
          phone?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      purchase_order_items: {
        Row: {
          created_at: string
          id: string
          purchase_order_id: string
          quantity: number
          subtotal: number
          unit_cost: number
          variant_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          purchase_order_id: string
          quantity: number
          subtotal: number
          unit_cost: number
          variant_id: string
        }
        Update: {
          created_at?: string
          id?: string
          purchase_order_id?: string
          quantity?: number
          subtotal?: number
          unit_cost?: number
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "purchase_order_items_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_order_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_order_payments: {
        Row: {
          amount: number
          created_at: string | null
          created_by: string | null
          id: string
          notes: string | null
          payment_date: string | null
          payment_method: string | null
          purchase_order_id: string | null
          reference_number: string | null
        }
        Insert: {
          amount: number
          created_at?: string | null
          created_by?: string | null
          id?: string
          notes?: string | null
          payment_date?: string | null
          payment_method?: string | null
          purchase_order_id?: string | null
          reference_number?: string | null
        }
        Update: {
          amount?: number
          created_at?: string | null
          created_by?: string | null
          id?: string
          notes?: string | null
          payment_date?: string | null
          payment_method?: string | null
          purchase_order_id?: string | null
          reference_number?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "purchase_order_payments_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_orders: {
        Row: {
          created_at: string
          created_by: string | null
          creditor_id: string
          customs_cost: number | null
          expected_date: string | null
          freight_cost: number | null
          handling_cost: number | null
          id: string
          notes: string | null
          order_number: string
          paid_amount: number
          received_at: string | null
          status: string
          total_amount: number
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          creditor_id: string
          customs_cost?: number | null
          expected_date?: string | null
          freight_cost?: number | null
          handling_cost?: number | null
          id?: string
          notes?: string | null
          order_number: string
          paid_amount?: number
          received_at?: string | null
          status?: string
          total_amount?: number
        }
        Update: {
          created_at?: string
          created_by?: string | null
          creditor_id?: string
          customs_cost?: number | null
          expected_date?: string | null
          freight_cost?: number | null
          handling_cost?: number | null
          id?: string
          notes?: string | null
          order_number?: string
          paid_amount?: number
          received_at?: string | null
          status?: string
          total_amount?: number
        }
        Relationships: [
          {
            foreignKeyName: "purchase_orders_creditor_id_fkey"
            columns: ["creditor_id"]
            isOneToOne: false
            referencedRelation: "creditors"
            referencedColumns: ["id"]
          },
        ]
      }
      raw_materials: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          quantity_in_stock: number | null
          reorder_level: number | null
          unit: string
          unit_cost: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          quantity_in_stock?: number | null
          reorder_level?: number | null
          unit: string
          unit_cost?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          quantity_in_stock?: number | null
          reorder_level?: number | null
          unit?: string
          unit_cost?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      recipe_items: {
        Row: {
          created_at: string | null
          id: string
          material_variant_id: string | null
          quantity: number
          recipe_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          material_variant_id?: string | null
          quantity: number
          recipe_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          material_variant_id?: string | null
          quantity?: number
          recipe_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipe_items_material_variant_id_fkey"
            columns: ["material_variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recipe_items_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      recipes: {
        Row: {
          created_at: string
          description: string | null
          id: string
          labor_cost: number | null
          machine_cost: number | null
          name: string
          product_variant_id: string | null
          yield_quantity: number
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          labor_cost?: number | null
          machine_cost?: number | null
          name: string
          product_variant_id?: string | null
          yield_quantity: number
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          labor_cost?: number | null
          machine_cost?: number | null
          name: string
          product_variant_id?: string | null
          yield_quantity: number
        }
        Relationships: [
          {
            foreignKeyName: "recipes_product_variant_id_fkey"
            columns: ["product_variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_feedback: {
        Row: {
          content: string
          created_at: string | null
          customer_id: string | null
          feedback_type: string
          follow_up_date: string | null
          id: string
          sales_rep_id: string
          status: string | null
        }
        Insert: {
          content: string
          created_at?: string | null
          customer_id?: string | null
          feedback_type: string
          follow_up_date?: string | null
          id?: string
          sales_rep_id: string
          status?: string | null
        }
        Update: {
          content?: string
          created_at?: string | null
          customer_id?: string | null
          feedback_type?: string
          follow_up_date?: string | null
          id?: string
          sales_rep_id?: string
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sales_feedback_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_order_items: {
        Row: {
          created_at: string | null
          discount: number | null
          id: string
          order_id: string
          quantity: number
          total_price: number
          unit_price: number
          variant_id: string
        }
        Insert: {
          created_at?: string | null
          discount?: number | null
          id?: string
          order_id: string
          quantity: number
          total_price: number
          unit_price: number
          variant_id: string
        }
        Update: {
          created_at?: string | null
          discount?: number | null
          id?: string
          order_id?: string
          quantity?: number
          total_price?: number
          unit_price?: number
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "sales_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_order_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_orders: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          created_at: string | null
          created_by: string | null
          customer_id: string | null
          delivery_address: string | null
          delivery_format: string | null
          discount_amount: number | null
          dispatched_at: string | null
          dispatched_by: string | null
          id: string
          is_credit_sale: boolean | null
          notes: string | null
          order_number: string
          payment_method: Database["public"]["Enums"]["payment_method"] | null
          status: Database["public"]["Enums"]["order_status"] | null
          subtotal: number | null
          tax_amount: number | null
          total_amount: number | null
          updated_at: string | null
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          created_by?: string | null
          customer_id?: string | null
          delivery_address?: string | null
          delivery_format?: string | null
          discount_amount?: number | null
          dispatched_at?: string | null
          dispatched_by?: string | null
          id?: string
          is_credit_sale?: boolean | null
          notes?: string | null
          order_number: string
          payment_method?: Database["public"]["Enums"]["payment_method"] | null
          status?: Database["public"]["Enums"]["order_status"] | null
          subtotal?: number | null
          tax_amount?: number | null
          total_amount?: number | null
          updated_at?: string | null
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          created_by?: string | null
          customer_id?: string | null
          delivery_address?: string | null
          delivery_format?: string | null
          discount_amount?: number | null
          dispatched_at?: string | null
          dispatched_by?: string | null
          id?: string
          is_credit_sale?: boolean | null
          notes?: string | null
          order_number?: string
          payment_method?: Database["public"]["Enums"]["payment_method"] | null
          status?: Database["public"]["Enums"]["order_status"] | null
          subtotal?: number | null
          tax_amount?: number | null
          total_amount?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sales_orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      customer_type: "individual" | "retail" | "wholesale" | "distributor"
      order_status:
      | "pending"
      | "approved"
      | "dispatched"
      | "delivered"
      | "cancelled"
      | "completed"
      payment_method: "cash" | "mpesa" | "bank_transfer" | "credit"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  PublicTableNameOrOptions extends
  | keyof (PublicSchema["Tables"] & PublicSchema["Views"])
  | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
  ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
    Database[PublicTableNameOrOptions["schema"]]["Views"])
  : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
    Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
  ? R
  : never
  : PublicTableNameOrOptions extends keyof (PublicSchema["Tables"] &
    PublicSchema["Views"])
  ? (PublicSchema["Tables"] &
    PublicSchema["Views"])[PublicTableNameOrOptions] extends {
      Row: infer R
    }
  ? R
  : never
  : never

export type TablesInsert<
  PublicTableNameOrOptions extends
  | keyof PublicSchema["Tables"]
  | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
  ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
  : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
    Insert: infer I
  }
  ? I
  : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
  ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
    Insert: infer I
  }
  ? I
  : never
  : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
  | keyof PublicSchema["Tables"]
  | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
  ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
  : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
    Update: infer U
  }
  ? U
  : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
  ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
    Update: infer U
  }
  ? U
  : never
  : never

export type Enums<
  PublicEnumNameOrOptions extends
  | keyof PublicSchema["Enums"]
  | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
  ? keyof Database[PublicTableNameOrOptions["schema"]]["Enums"]
  : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema["Enums"]
  ? PublicSchema["Enums"][PublicEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
  | keyof PublicSchema["CompositeTypes"]
  | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
  ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
  : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof PublicSchema["CompositeTypes"]
  ? PublicSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never
